<?php

/**
 *	Implementation of hook_form_alter().
 *	Change the normal login form behavior.
 **/

function ldap_jacobs_basic_form_alter( &$form, $form_state, $form_id ){
	if($form_id == 'user_login_block' || $form_id == 'user_login' ){
		$form['#validate'] = array( 'user_login_name_validate', 'user_login_authenticate_validate', 'ldap_jacobs_basic_login_validate', 'user_login_final_validate' );
	}



}




/**
 * The function that checks if the credentials are valid and correct
 *
 */

function ldap_jacobs_basic_check_user($username, $password){
		$r = new LdapSearch;
		$r->connect();

		$user = user_load_by_name($username);
		if($user && ($user->name != $user->init)){
			return false;
		}
		else{
			if ($r->bind($username, $password)) drupal_set_message(t("LDAP login!"));
			return ($r->bind($username, $password));
		}

}


/**
 *	The ldap_jacobs_auth() function attempts to authenticate a user off the external system using their e-mail address
 *
 **/

function ldap_jacobs_basic_login_validate( $form, &$form_state){
	$username = $form_state['values']['name'];
	$response = ldap_jacobs_basic_check_user($username, $form_state['values']['pass'] );
	if ($response != false){
		user_external_login_register($username, 'ldap_jacobs_basic');
		$account = user_external_load($username);
		$form_state['uid'] = $account->uid;

		
	}

}










?>